const SPOTS = {
  'lingshan-buddha': {
    id: 'lingshan-buddha',
    name: '灵山大佛',
    category: '青铜佛像·世界之最',
    heroGradient: 'linear-gradient(160deg, #1a3a2a 0%, #2a5a3a 30%, #5a8a4a 70%, #3a6a2a 100%)',
    oneLiner: '世界最高露天青铜释迦牟尼立像，通高88米，总高101.5米。',
    shortIntro: '灵山大佛位于无锡灵山胜境秦履峰南侧，是世界上最高的露天青铜释迦牟尼立像。佛像通高88米（佛体79米+莲花瓣9米），含台基总高101.5米，总用铜量725吨。右手施无畏印除却众生痛苦，左手施与愿印赐予众生欢乐。登216级登云道抱佛脚，俯瞰太湖全景。',
    fullIntro: '灵山大佛位于无锡灵山胜境秦履峰南侧，矗立在景区最高处，是世界上最高的露天青铜释迦牟尼立像，也是灵山胜境的核心地标。\n\n佛像通高88米（佛体79米，莲花瓣9米），含台基总高101.5米，总用铜量达725吨，佛体由1560块6-8毫米厚的铜壁板构成，焊缝总长度逾35公里。建造历时3年（1994-1997年），采用现代高科技与传统工艺相结合的方式。\n\n在佛教意义上，大佛右手施无畏印，代表除却众生痛苦；左手施与愿印，代表赐予众生欢乐。通往大佛的216级登云道暗合佛教108烦恼与108愿望，前108级寓意"烦恼尽除"，后108级寓意"愿望圆满"。\n\n最佳体验：登顶抱佛脚，俯瞰太湖全景；在夕阳西下时拍摄，金色阳光洒在大佛身上。',
    source: '灵山胜境官方资料 · 示范景区公开资料包',
    audioDuration: '3:30',
    related: ['lingshan-fanpalace', 'lingshan-jiulong', 'lingshan-mandala'],
  },
  'lingshan-fanpalace': {
    id: 'lingshan-fanpalace',
    name: '灵山梵宫',
    category: '佛教艺术殿堂',
    heroGradient: 'linear-gradient(160deg, #3a2a1a 0%, #5a3a2a 30%, #8a5a3a 70%, #5a3a1a 100%)',
    oneLiner: '"东方卢浮宫"，世界佛教论坛永久会址，融合非遗艺术的殿堂。',
    shortIntro: '灵山梵宫建筑面积7.2万平方米，最高处66.5米，造价18亿。内部汇集东阳木雕、琉璃、油画、景泰蓝等传统工艺，五座莲花圣塔象征五方五佛。28米高星空穹顶用100公斤纯金绘制，160块琉璃构件拼成《华藏世界》巨制。',
    fullIntro: '灵山梵宫位于灵山胜境西侧香水海之畔，建筑面积达7.2万平方米，最高处66.5米，整体呈"莲花环抱"之势，拥有五座错落分布的莲花圣塔，被誉为"东方卢浮宫"。\n\n梵宫内部堪称艺术殿堂：廊厅两侧12幅高12米宽3米的"世界佛教传法图"油画；中庭28米高星空穹顶用100公斤纯金绘制，148尊飞天姿态各异；核心琉璃巨制《华藏世界》宽8米高10米，由160块彩色琉璃拼接而成。\n\n梵宫是第二、四届世界佛教论坛的永久会址，圣坛可容纳2000人同时观演。每日上演《灵山吉祥颂》大型演出（10:35/11:30/14:00/16:00）。',
    source: '灵山胜境官方资料 · 示范景区公开资料包',
    audioDuration: '4:00',
    related: ['lingshan-buddha', 'lingshan-mandala', 'lingshan-jiulong'],
  },
  'lingshan-jiulong': {
    id: 'lingshan-jiulong',
    name: '九龙灌浴',
    category: '动态音乐群雕',
    heroGradient: 'linear-gradient(160deg, #1a3a5a 0%, #2a4a6a 30%, #3a6a8a 70%, #1a4a6a 100%)',
    oneLiner: '大型音乐动态群雕，重现释迦牟尼诞生"花开见佛"祥瑞场景。',
    shortIntro: '九龙灌浴总高27.2米，青铜重量260吨，中央为7.2米高鎏金太子佛像。每日4-5场表演，莲花瓣缓缓开启，太子佛在九龙喷泉与《佛诞颂》音乐中旋转升起，九龙吐水为太子沐浴，水幕与阳光交织出七彩佛光。',
    fullIntro: '九龙灌浴位于灵山胜境中轴线核心位置，总高27.2米，青铜重量260吨，中央为7.2米高、重12吨的鎏金太子佛像。大型音乐动态群雕依据《本行经》中释迦牟尼诞生的传说精心打造。\n\n表演时，莲花铜雕缓缓绽放，太子佛从莲花中升起并自转一周，九条飞龙同时喷出水柱高达数十米，精准沐浴在太子佛身上。平日演出时间：10:00、11:30、13:30、15:00；每场时长约15分钟。表演结束后可接取祈福圣水。',
    source: '灵山胜境官方资料 · 示范景区公开资料包',
    audioDuration: '2:45',
    related: ['lingshan-buddha', 'lingshan-fanpalace', 'lingshan-xiangfu'],
  },
  'lingshan-mandala': {
    id: 'lingshan-mandala',
    name: '五印坛城',
    category: '藏传佛教文化',
    heroGradient: 'linear-gradient(160deg, #3a1a2a 0%, #5a1a3a 30%, #8a2a4a 70%, #5a1a3a 100%)',
    oneLiner: '"小布达拉宫"，藏传佛教文化瑰宝，四面环水的湖心圣殿。',
    shortIntro: '五印坛城位于香水海中央独立圆岛上，五层重檐楼宇，总高约30米，占地5000㎡。藏式碉楼风格，白墙红边金顶。坛城内设转经筒长廊（108个纯铜转经筒）、唐卡展厅和藏传佛教文物陈列，展现汉藏佛教文化交融。',
    fullIntro: '五印坛城位于香水海中央的独立圆岛上，通过景观栈道与灵山梵宫相连。建筑为五层重檐楼宇，总高约30米，占地5000㎡，整体采用藏式碉楼风格，白墙红边金顶。\n\n"五印"代表五方五佛的五种手印，坛城是藏传佛教中的曼陀罗道场，象征着宇宙的和谐与圆满。转经筒长廊环绕主殿，摆放108个纯铜转经筒，游客可顺时针转动，寓意祈福消灾。\n\n登至五层顶层观景台，可俯瞰香水海、灵山梵宫与灵山大佛全景。',
    source: '灵山胜境官方资料 · 示范景区公开资料包',
    audioDuration: '2:15',
    related: ['lingshan-fanpalace', 'lingshan-buddha', 'lingshan-xiangfu'],
  },
  'lingshan-xiangfu': {
    id: 'lingshan-xiangfu',
    name: '祥符禅寺',
    category: '千年古刹',
    heroGradient: 'linear-gradient(160deg, #2a3a1a 0%, #3a4a2a 30%, #4a5a3a 70%, #2a3a1a 100%)',
    oneLiner: '唐代古刹，玄奘法师弟子开坛讲经之地，千年银杏见证兴衰。',
    shortIntro: '祥符禅寺始建于唐贞观年间，由玄奘法师弟子窥基大师开坛讲经。北宋大中祥符年间赐额"祥符禅寺"，占地约30亩。寺内有千年银杏、六角古井等珍贵历史遗迹，钟楼内悬挂重12.8吨的"祥符禅钟"。',
    fullIntro: '祥符禅寺位于灵山胜境中轴核心，始建于唐贞观年间，与玄奘法师西行取经的壮举紧密相连——玄奘法师途经马山时见此地山形酷似印度灵鹫山，遂命名为"小灵山"，并嘱咐大弟子窥基法师在此住持道场。\n\n北宋大中祥符年间，宋真宗赐额"祥符禅寺"。寺内珍贵遗存：千年银杏树龄超千年，秋季金黄树叶铺满寺院；六角井为唐代名泉，曾被茶圣陆羽品鉴；钟楼内的祥符禅钟重12.8吨，钟声悠扬，响彻太湖之滨。',
    source: '灵山胜境官方资料 · 示范景区公开资料包',
    audioDuration: '2:00',
    related: ['lingshan-buddha', 'lingshan-jiulong', 'lingshan-fanpalace'],
  },
  'lingshan-dazhaobi': {
    id: 'lingshan-dazhaobi',
    name: '灵山大照壁',
    category: '景区门户',
    heroGradient: 'linear-gradient(160deg, #1a3a2a 0%, #2a4a3a 30%, #3a5a3a 70%, #1a3a2a 100%)',
    oneLiner: '"华夏第一壁"，赵朴初先生亲笔题写鎏金"灵山胜境"四字。',
    shortIntro: '灵山大照壁位于景区入口处，长39.8m，高7m，采用优质青石雕刻而成，被誉为"华夏第一壁"。正面鎏金大字由赵朴初先生题写，北立面刻有赵老诗作《小灵山》。',
    fullIntro: '照壁采用优质青石精心雕刻，正面鎏金大字由赵朴初先生题写，笔力遒劲，鎏金工艺让字体在阳光下熠熠生辉。北立面刻有赵老诗作《小灵山》，诗中对比印度灵鹫山与中国小灵山，彰显中华佛教文化的自信与底蕴。',
    source: '灵山胜境官方资料 · 示范景区公开资料包',
    audioDuration: '1:30',
    related: ['lingshan-wuzhimen', 'lingshan-xiangfu'],
  },
  'lingshan-manfeilong': {
    id: 'lingshan-manfeilong',
    name: '曼飞龙塔',
    category: '南传佛教建筑',
    heroGradient: 'linear-gradient(160deg, #4a3a2a 0%, #6a5a3a 30%, #8a7a4a 70%, #5a4a2a 100%)',
    oneLiner: '复刻西双版纳曼飞龙白塔，南传佛教标志性建筑。',
    shortIntro: '曼飞龙塔主塔高16.9m，由一座主塔和八座小塔组成九塔组合。复刻云南西双版纳曼飞龙白塔，是南传佛教标志性建筑。',
    fullIntro: '曼飞龙塔又称"白塔"，完全复刻了云南西双版纳曼飞龙白塔的形制与工艺。主塔矗立在圆形须弥座中央，塔身呈葫芦状，八座小塔环绕主塔分布，呈八角形排列，形成"众星拱月"的格局。',
    source: '灵山胜境官方资料 · 示范景区公开资料包',
    audioDuration: '1:45',
    related: ['lingshan-mandala', 'lingshan-fanpalace'],
  },
  'lingshan-wuzhimen': {
    id: 'lingshan-wuzhimen',
    name: '五智门',
    category: '核心门户',
    heroGradient: 'linear-gradient(160deg, #2a2a3a 0%, #3a3a4a 30%, #4a4a5a 70%, #2a2a3a 100%)',
    oneLiner: '五门六柱石牌坊，穿过此门正式踏入禅意圣地。',
    shortIntro: '五智门高16.8m，宽35m，五门六柱汉白玉石牌坊。五门象征五方五佛，六柱代表佛教"六度波罗蜜"。',
    fullIntro: '五智门由优质汉白玉精雕细琢而成，雕刻工艺精湛绝伦。整座牌坊气势恢宏，矗立在景区中轴线上，与后方的灵山大佛在同一直线上。',
    source: '灵山胜境官方资料 · 示范景区公开资料包',
    audioDuration: '1:30',
    related: ['lingshan-dazhaobi', 'lingshan-buddha', 'lingshan-xiangfu'],
  },
}

const ROUTES = [
  {
    id: 'history',
    title: '历史文化爱好者路线',
    description: '深度探访灵山胜境千年佛教文化，从唐代古刹到当代艺术殿堂。',
    duration: '约6小时',
    distance: '5.2 km',
    difficulty: '中等',
    tags: ['推荐', '深度', '人文'],
    steps: [
      { spot: '南门入园', duration: '—', note: '扫码入园，领取电子导览' },
      { spot: '灵山大照壁', duration: '10分钟', note: '华夏第一壁，39.8米浮雕全景' },
      { spot: '佛手广场', duration: '15分钟', note: '天下第一掌，摸掌祈福' },
      { spot: '祥符禅寺', duration: '30分钟', note: '千年古刹，玄奘法师渊源' },
      { spot: '灵山大佛', duration: '60分钟', note: '登216级登云道，抱佛脚，俯瞰太湖' },
      { spot: '灵山梵宫', duration: '90分钟', note: '佛教艺术殿堂，赏《吉祥颂》演出' },
      { spot: '五印坛城', duration: '45分钟', note: '藏传佛教文化，转经筒祈福' },
      { spot: '出口', duration: '—', note: '结束游览' },
    ],
  },
  {
    id: 'nature',
    title: '自然风光爱好者路线',
    description: '徜徉于太湖之滨、青龙白虎山环抱之间，感受佛教文化与自然的完美融合。',
    duration: '约5小时',
    distance: '4.5 km',
    difficulty: '轻松',
    tags: ['风光', '休闲', '拍照'],
    steps: [
      { spot: '南门入园', duration: '—', note: '扫码入园' },
      { spot: '佛足坛', duration: '10分钟', note: '佛教文化起点' },
      { spot: '九龙灌浴', duration: '20分钟', note: '观赏动态表演，接取祈福圣水' },
      { spot: '菩提大道', duration: '20分钟', note: '漫步林荫道，欣赏太湖风光' },
      { spot: '灵山大佛', duration: '50分钟', note: '登顶俯瞰太湖全景，拍佛光日落' },
      { spot: '曼飞龙塔', duration: '20分钟', note: '傣族佛教建筑，园林景观' },
      { spot: '灵山精舍', duration: '30分钟', note: '禅意园林，品尝素斋' },
      { spot: '出口', duration: '—', note: '结束游览' },
    ],
  },
  {
    id: 'family',
    title: '亲子家庭路线',
    description: '节奏轻松、互动丰富，让孩子在玩乐中感受传统文化魅力。',
    duration: '约4小时',
    distance: '3.0 km',
    difficulty: '轻松',
    tags: ['亲子', '轻松', '互动'],
    steps: [
      { spot: '南门入园', duration: '—', note: '靠近停车场，步行便捷' },
      { spot: '九龙灌浴', duration: '25分钟', note: '动态群雕表演，孩子最爱"花开见佛"' },
      { spot: '佛手广场', duration: '15分钟', note: '摸天下第一掌，沾福气' },
      { spot: '百子戏弥勒', duration: '15分钟', note: '亲子互动拍照' },
      { spot: '灵山大佛', duration: '40分钟', note: '全家一起登顶抱佛脚' },
      { spot: '灵山梵宫', duration: '60分钟', note: '观看《吉祥颂》演出' },
      { spot: '五印坛城', duration: '30分钟', note: '转动108个转经筒' },
      { spot: '出口', duration: '—', note: '出口旁有素面餐厅' },
    ],
  },
]

const MOCK_KNOWLEDGE = {
  '灵山大佛': {
    text: '灵山大佛位于无锡灵山胜境秦履峰南侧，是世界上最高的露天青铜释迦牟尼立像。佛像通高88米（佛体79米+莲花瓣9米），含台基总高101.5米，总用铜量725吨。右手施无畏印除却众生痛苦，左手施与愿印赐予众生欢乐。登216级登云道抱佛脚，俯瞰太湖全景。',
    source: '灵山胜境官方资料',
  },
  '灵山梵宫': {
    text: '灵山梵宫建筑面积7.2万平方米，最高处66.5米，造价18亿，被誉为"东方卢浮宫"。内部汇集东阳木雕、琉璃、油画等传统工艺，28米高星空穹顶用100公斤纯金绘制。每日上演《灵山吉祥颂》大型演出。',
    source: '灵山胜境官方资料',
  },
  '推荐路线': {
    text: '推荐路线：南门入园 → 灵山大照壁 → 佛手广场 → 祥符禅寺 → 灵山大佛（登顶抱佛脚）→ 灵山梵宫（艺术殿堂深度游）→ 五印坛城（藏传佛教文化体验）→ 出口。全程约6小时。',
    source: '灵山胜境官方资料',
  },
  default: {
    text: '灵山胜境位于江苏省无锡市太湖西北部的马山镇，是国家5A级旅游景区、世界佛教论坛永久会址，被誉为"东方佛国"。景区占地面积约30万平方米，历史可追溯至1300多年前的唐代贞观年间。',
    source: '灵山胜境官方资料',
  },
}

const TIERS = [
  { key: 'oneLiner', label: '一句话', icon: '⏱' },
  { key: 'shortIntro', label: '30秒', icon: '⏱' },
  { key: 'fullIntro', label: '3分钟', icon: '📖' },
]

const QUICK_ACTIONS = [
  { icon: '🗺', label: '推荐路线', action: 'route' },
  { icon: '📷', label: '拍照识景', action: 'camera' },
  { icon: '📖', label: '深度讲解', action: 'detail' },
  { icon: '⏱', label: '游览时长', action: 'ask' },
]

module.exports = {
  SPOTS,
  ROUTES,
  MOCK_KNOWLEDGE,
  TIERS,
  QUICK_ACTIONS,
}
